import { IMPOSSIBLE, VersionInfo } from '@start9labs/start-sdk'

export const current = VersionInfo.of({
  version: '6.4.5:0',
  releaseNotes: {
    en_US:
      'Chama 6.4.5 makes your name travel and your numbers honest. A profile name you save is published to Nostr — merged into any profile you already have, never overwriting it — so it follows your key to every device and client, and a chosen name now replaces the generated one entirely. Identity moves into its own Profile tab (name, how others see you, appearance, language). The sats/fiat switch finally reaches Me, a circle host no longer sees every member\'s seat counted as their own money, stale ghost orders clear out of the seller queue, and sandbox trades stop leaking into real history. The "in escrow" pill is tappable and shows you which trade it means; expired listings, the Lightning Addresses panel and failed claims on old trades all explain themselves instead of dead-ending. No data migration.',
    es_ES:
      'Chama 6.4.5 hace que tu nombre viaje y que tus números sean honestos. El nombre de perfil que guardas se publica en Nostr — fusionado con el perfil que ya tengas, nunca sobrescrito — así te sigue con tu llave a cada dispositivo y cliente, y el nombre elegido sustituye por completo al generado. La identidad pasa a su propia pestaña Perfil (nombre, cómo te ven, apariencia, idioma). El interruptor sats/fiat ya llega a Yo, el anfitrión de un círculo deja de ver el asiento de cada miembro contado como dinero suyo, las órdenes fantasma se limpian de la cola del vendedor y las operaciones de prueba dejan de filtrarse al historial real. La píldora "en custodia" ahora se pulsa y te muestra a qué operación se refiere; las ofertas expiradas, el panel de Direcciones Lightning y los cobros fallidos de operaciones antiguas se explican en vez de quedarse en un callejón sin salida. Sin migración de datos.',
    de_DE:
      'Chama 6.4.5 lässt deinen Namen mitreisen und macht deine Zahlen ehrlich. Ein gespeicherter Profilname wird auf Nostr veröffentlicht — in ein vorhandenes Profil eingefügt, nie überschrieben — und folgt so deinem Schlüssel auf jedes Gerät und in jeden Client; ein gewählter Name ersetzt den generierten vollständig. Die Identität bekommt einen eigenen Profil-Tab (Name, wie andere dich sehen, Erscheinungsbild, Sprache). Der Sats/Fiat-Schalter erreicht endlich „Ich", ein Kreis-Gastgeber sieht nicht mehr jeden fremden Platz als eigenes Geld gezählt, Geisteraufträge räumen sich aus der Verkäuferliste, und Sandbox-Trades sickern nicht mehr in die echte Historie. Die „im Treuhandkonto"-Pille ist antippbar und zeigt, welcher Trade gemeint ist; abgelaufene Angebote, das Lightning-Adressen-Panel und fehlgeschlagene Auszahlungen alter Trades erklären sich selbst, statt in einer Sackgasse zu enden. Keine Datenmigration.',
    pl_PL:
      'Chama 6.4.5 sprawia, że twoje imię podróżuje, a liczby są uczciwe. Zapisana nazwa profilu jest publikowana w Nostr — scalona z profilem, który już masz, nigdy nadpisana — więc podąża za twoim kluczem na każde urządzenie i do każdego klienta, a wybrana nazwa całkowicie zastępuje wygenerowaną. Tożsamość dostaje własną zakładkę Profil (nazwa, jak widzą cię inni, wygląd, język). Przełącznik sats/fiat wreszcie dociera do zakładki Ja, gospodarz kręgu nie widzi już miejsca każdego uczestnika liczonego jako własne pieniądze, widmowe zamówienia znikają z kolejki sprzedawcy, a transakcje z piaskownicy nie przeciekają do prawdziwej historii. Pigułka „w depozycie" jest klikalna i pokazuje, o którą transakcję chodzi; wygasłe oferty, panel adresów Lightning i nieudane odbiory starych transakcji tłumaczą się same zamiast kończyć w ślepym zaułku. Bez migracji danych.',
    fr_FR:
      "Chama 6.4.5 fait voyager votre nom et rend vos chiffres honnêtes. Un nom de profil enregistré est publié sur Nostr — fusionné avec le profil que vous avez déjà, jamais écrasé — il suit donc votre clé sur chaque appareil et dans chaque client, et un nom choisi remplace entièrement celui généré. L'identité gagne son propre onglet Profil (nom, comment les autres vous voient, apparence, langue). Le commutateur sats/fiat atteint enfin Moi, l'hôte d'un cercle ne voit plus la place de chaque membre comptée comme son propre argent, les commandes fantômes se vident de la file du vendeur, et les échanges du bac à sable ne fuient plus dans l'historique réel. La pastille « sous séquestre » est cliquable et montre de quel échange il s'agit ; les annonces expirées, le panneau Adresses Lightning et les encaissements ratés d'anciens échanges s'expliquent au lieu de finir en impasse. Aucune migration de données.",
  },
  migrations: {
    up: async ({ effects }) => {},
    down: IMPOSSIBLE,
  },
})
