import { IMPOSSIBLE, VersionInfo } from '@start9labs/start-sdk'

export const current = VersionInfo.of({
  version: '6.4.10:0',
  releaseNotes: {
    en_US:
      "Chama 6.4.10 brings on-chain trading to everyone. Post an offer of 100,000 sats or more and it's on-chain by default, right from the guided flow; from 25,000 sats it's there as an option, with the fees shown before you post. Send the deposit from any wallet, and Chama locks the trade by itself once it confirms. Confirming that you got paid now signs the payout at the same time, so nobody can agree and then leave the other person hanging — and a key that ever does gets a red mark everyone can see. Whenever a trade is waiting on you, the bar lights up and you get a notification. You can claim straight into Fedi with its receive code, and you can see how quickly people sign and how long they've been bonded, based on proof rather than promises. Circles don't rotate yet — that's coming in 6.5. Nothing to migrate: just update.",
    es_ES:
      "Chama 6.4.10 trae las operaciones on-chain a todo el mundo. Publica una oferta de 100.000 sats o más y será on-chain por defecto, directamente desde el flujo guiado; desde 25.000 sats está disponible como opción, con las comisiones a la vista antes de publicar. Envía el depósito desde cualquier monedero y Chama bloquea la operación sola cuando se confirma. Confirmar que recibiste el pago ahora también firma el cobro, así nadie puede aceptar y luego dejar colgada a la otra persona; y la clave que lo haga recibe una marca roja que todos pueden ver. Cuando una operación te espera, la barra se enciende y recibes una notificación. Puedes cobrar directamente en Fedi con su código de recepción, y ver cuán rápido firma la gente y cuánto tiempo lleva con fianza, basado en pruebas y no en promesas. Los círculos todavía no rotan: eso llega en 6.5. No hay nada que migrar: solo actualiza.",
    de_DE:
      "Chama 6.4.10 bringt On-Chain-Handel für alle. Stell ein Angebot ab 100.000 Sats ein und es läuft standardmäßig on-chain, direkt aus dem geführten Ablauf; ab 25.000 Sats steht es als Option bereit, mit den Gebühren sichtbar vor dem Einstellen. Schick die Einzahlung aus einer beliebigen Wallet, und Chama sperrt den Trade von selbst, sobald sie bestätigt ist. Wer bestätigt, bezahlt worden zu sein, unterschreibt jetzt gleichzeitig die Auszahlung – niemand kann mehr zustimmen und die andere Person dann hängen lassen, und ein Schlüssel, der das je tut, bekommt eine rote Markierung, die alle sehen. Wartet ein Trade auf dich, leuchtet die Leiste auf und du bekommst eine Benachrichtigung. Du kannst direkt in Fedi mit dessen Empfangscode auszahlen lassen und siehst, wie schnell Leute unterschreiben und wie lange sie gebondet sind – belegt statt versprochen. Kreise rotieren noch nicht – das kommt mit 6.5. Nichts zu migrieren: einfach aktualisieren.",
    pl_PL:
      "Chama 6.4.10 udostępnia handel on-chain wszystkim. Wystaw ofertę na 100 000 satsów lub więcej, a będzie on-chain domyślnie, prosto z trybu prowadzonego; od 25 000 satsów jest dostępna jako opcja, z opłatami widocznymi przed publikacją. Wyślij depozyt z dowolnego portfela, a Chama sama zablokuje transakcję po potwierdzeniu. Potwierdzenie, że otrzymałeś zapłatę, teraz od razu podpisuje wypłatę, więc nikt nie może się zgodzić i zostawić drugiej osoby na lodzie — a klucz, który kiedykolwiek to zrobi, dostaje czerwony znak widoczny dla wszystkich. Gdy transakcja czeka na ciebie, pasek się podświetla i dostajesz powiadomienie. Możesz odebrać satsy prosto do Fedi jego kodem odbioru i zobaczyć, jak szybko ludzie podpisują i jak długo mają kaucję — na podstawie dowodów, nie obietnic. Kręgi jeszcze się nie obracają — to przyjdzie w 6.5. Nic do migracji: po prostu zaktualizuj.",
    fr_FR:
      "Chama 6.4.10 ouvre les échanges on-chain à tout le monde. Publiez une offre de 100 000 sats ou plus et elle est on-chain par défaut, directement depuis le parcours guidé ; dès 25 000 sats, c'est une option, avec les frais affichés avant de publier. Envoyez le dépôt depuis n'importe quel portefeuille, et Chama verrouille l'échange tout seul une fois confirmé. Confirmer que vous avez été payé signe désormais le versement en même temps : personne ne peut plus accepter puis laisser l'autre en plan, et une clé qui le fait un jour reçoit une marque rouge visible par tous. Quand un échange vous attend, la barre s'allume et vous recevez une notification. Vous pouvez encaisser directement dans Fedi avec son code de réception, et voir à quelle vitesse les gens signent et depuis combien de temps ils ont une caution — prouvé, pas promis. Les cercles ne tournent pas encore — ce sera pour 6.5. Rien à migrer : il suffit de mettre à jour.",
  },
  migrations: {
    up: async ({ effects }) => {},
    down: IMPOSSIBLE,
  },
})
