import { IMPOSSIBLE, VersionInfo } from '@start9labs/start-sdk'

export const current = VersionInfo.of({
  version: '6.4.9:0',
  releaseNotes: {
    en_US:
      "Chama 6.4.9 makes on-chain trades something you can count on. Before the first real on-chain trade, we tried hard to break the escrow — and fixed every way we found. Now both sides agree on the deposit address and keys up front, and a lock that doesn't match is simply refused. The person waiting checks the deposit on the blockchain itself, and refunds and disputes work the way they promise. We tested all of it on a real test network: a normal release, a dispute, a refund, an early refund (blocked, as it should be) and a cheating attempt (caught). Offers got fairer too: \"Lowest price\" now points to the offer that gives you the most sats for your money, and Bill Pay offers say plainly that you're paying someone's bill for sats. Circles don't rotate yet — that's coming in 6.5. Nothing to migrate: just update.",
    es_ES:
      "Chama 6.4.9 hace que las operaciones on-chain sean algo en lo que puedes confiar. Antes de la primera operación on-chain real, intentamos romper el depósito en garantía con todas nuestras fuerzas, y arreglamos cada fallo que encontramos. Ahora ambas partes acuerdan de antemano la dirección del depósito y las claves, y un bloqueo que no coincide simplemente se rechaza. Quien espera comprueba el depósito directamente en la blockchain, y los reembolsos y las disputas funcionan como prometen. Lo probamos todo en una red de pruebas real: una liberación normal, una disputa, un reembolso, un reembolso anticipado (bloqueado, como debe ser) y un intento de trampa (detectado). Las ofertas también son más justas: \"Precio más bajo\" ahora señala la oferta que te da más sats por tu dinero, y las ofertas de Pago de facturas dicen claramente que pagas la factura de alguien a cambio de sats. Los círculos todavía no rotan: eso llega en 6.5. No hay nada que migrar: solo actualiza.",
    de_DE:
      "Chama 6.4.9 macht On-Chain-Trades zu etwas, worauf du dich verlassen kannst. Vor dem ersten echten On-Chain-Trade haben wir mit aller Kraft versucht, das Treuhandkonto zu knacken – und jede gefundene Schwachstelle behoben. Jetzt einigen sich beide Seiten vorab auf die Einzahlungsadresse und die Schlüssel, und eine Sperre, die nicht passt, wird einfach abgelehnt. Wer wartet, prüft die Einzahlung direkt auf der Blockchain, und Rückerstattungen und Streitfälle funktionieren wie versprochen. Wir haben alles in einem echten Testnetz geprüft: eine normale Freigabe, einen Streitfall, eine Rückerstattung, eine zu frühe Rückerstattung (blockiert, wie es sein soll) und einen Betrugsversuch (erkannt). Auch die Angebote sind fairer: „Niedrigster Preis“ zeigt jetzt das Angebot, das dir die meisten Sats für dein Geld gibt, und Rechnungsangebote sagen klar, dass du jemandes Rechnung gegen Sats bezahlst. Kreise rotieren noch nicht – das kommt mit 6.5. Nichts zu migrieren: einfach aktualisieren.",
    pl_PL:
      "Chama 6.4.9 sprawia, że transakcje on-chain są czymś, na czym możesz polegać. Przed pierwszą prawdziwą transakcją on-chain z całych sił próbowaliśmy złamać depozyt — i naprawiliśmy każdą słabość, którą znaleźliśmy. Teraz obie strony z góry uzgadniają adres depozytu i klucze, a blokada, która się nie zgadza, jest po prostu odrzucana. Osoba czekająca sprawdza wpłatę bezpośrednio w blockchainie, a zwroty i spory działają tak, jak obiecują. Przetestowaliśmy wszystko w prawdziwej sieci testowej: zwykłe zwolnienie, spór, zwrot, zbyt wczesny zwrot (zablokowany, jak należy) i próbę oszustwa (wykrytą). Oferty też są uczciwsze: „Najniższa cena” wskazuje teraz ofertę, która daje ci najwięcej satsów za twoje pieniądze, a oferty płatności rachunków jasno mówią, że płacisz czyjś rachunek w zamian za satsy. Kręgi jeszcze się nie obracają — to przyjdzie w 6.5. Nic do migracji: po prostu zaktualizuj.",
    fr_FR:
      "Chama 6.4.9 rend les échanges on-chain dignes de confiance. Avant le premier vrai échange on-chain, nous avons tout fait pour casser le séquestre — et corrigé chaque faille trouvée. Désormais, les deux parties s'accordent dès le départ sur l'adresse de dépôt et les clés, et un verrouillage qui ne correspond pas est tout simplement refusé. La personne qui attend vérifie le dépôt directement sur la blockchain, et les remboursements comme les litiges fonctionnent comme promis. Nous avons tout testé sur un vrai réseau de test : une libération normale, un litige, un remboursement, un remboursement anticipé (bloqué, comme il se doit) et une tentative de triche (détectée). Les offres sont aussi plus justes : « Prix le plus bas » désigne maintenant l'offre qui vous donne le plus de sats pour votre argent, et les offres de paiement de factures disent clairement que vous payez la facture de quelqu'un contre des sats. Les cercles ne tournent pas encore — ce sera pour 6.5. Rien à migrer : il suffit de mettre à jour.",
  },
  migrations: {
    up: async ({ effects }) => {},
    down: IMPOSSIBLE,
  },
})
